### ISSUE TITLE
Missing Test Connection result in error using the custom connector in PBI service (with personal gateway)

### ISSUE THREAD

**Issue by alex-zak** [fortify-ps/FortifyPowerQueryConnectors#1]
please add the test connection function as defined here: 
https://learn.microsoft.com/en-us/power-query/samples/trippin/9-testconnection/readme

example:
FortifyOnDemand = [
    TestConnection = (dataSourcePath) => {"FortifyOnDemand.Contents"},
    Authentication = [

**Comment by alex-zak** [comment]
here a commit on my branch
https://github.com/alex-zak/FortifyPowerQueryConnectors/commit/4070dd358b8e827660cbd29557eb682806b179c2

**Comment by MikeTheSnowman** [comment]
Hello @alex-zak . Appologies for the very delayed reply. I've since performed a large refactoring of this project.

Can you explain to be very quick that adding `TestConnection` does? After reading the documentaiton that you pointed out, it's not immediately clear to be what's going on.
