### ISSUE TITLE
extract number of scans / project 

### ISSUE THREAD

**Issue by Rlima999** [fortify-ps/FortifyPowerQueryConnectors#3]
I'm using last version [v0.4-beta (Fortify SSC) and I would like to extract number of scans / project but when i select id from "listprojectversion" and add on parentid in listArtifactOfProjectVersion i do not have the number of scans.

Anyone can help or have same isse?

Thanks

**Comment by MikeTheSnowman** [comment]
Hey @Rlima999. Appologies the the severly delayed response. Do you still require assistance for this issue?
