### ISSUE TITLE
Fortify SSC API to PowerBI Not Running

### ISSUE THREAD

**Issue by JethaNh2** [fortify-ps/FortifyPowerQueryConnectors#5]
Hi,
Our client is facing uploading issue for Fortify SSC API to PowerBI

It looks like not running or loading with a message "Waiting for FortifyConnector.SSC." Below is the error message screenshot.

![PowerBI error](https://github.com/fortify-ps/FortifyPowerQueryConnectors/assets/164443469/da6c4cfa-ece4-41dc-8d34-692b062d9154)

Looking forward to your assistance.

**Comment by MikeTheSnowman** [comment]
Hey @JethaNh2 . That's a new issue I haven't encountered before. I have a few questions for you.

1. What steps did you go through before encountering this issue?
2. In your environment, do you need to connect to a proxy in order to access the SSC server?

**Comment by JethaNh2** [comment]
++loop in stakeholders


Hi @M Hafizan Abd Rahim ***@***.***>,

Could you share with us on below details?

Kindest regards,
***@***.***

**Comment by JethaNh2** [comment]
[Open]


[Open]

Dear @M Aamir Khan ***@***.***>,

Please help to provide requested details as per below email

Regards,
M Hafizan Abd Rahim

From: Jethashire Ravichandren ***@***.***>
Sent: Monday, March 25, 2024 9:09 AM
To: fortify-ps/FortifyPowerQueryConnectors ***@***.***>; fortify-ps/FortifyPowerQueryConnectors ***@***.***>; M Hafizan Abd Rahim (CS/DIGITAL) ***@***.***>; M Hafizan Abd Rahim (CS/DIGITAL) ***@***.***>
Cc: Mention ***@***.***>; NH2 Support ***@***.***>; Sathish Kumar (CS/DIGITAL) ***@***.***>; Nurainil Bt M Mustapa (CS/DIGITAL) ***@***.***>; Yap Kwan Hui (CS/DIGITAL) ***@***.***>; M Aamir Khan (EXT/DIGITAL) ***@***.***>; Hee Jia Yi ***@***.***>
Subject: RE: [fortify-ps/FortifyPowerQueryConnectors] Fortify SSC API to PowerBI Not Running (Issue #5)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

++loop in stakeholders


Hi @M Hafizan Abd Rahim ***@***.***>,

Could you share with us on below details?

Kindest regards,
***@***.***

**Comment by MikeTheSnowman** [comment]
Hey @JethaNh2 .
Just as a heads up, be careful when careful when replying back to the github email as you did above. The github reply included a link to unsibscribe your account from notifications for this issue. I just now modified your last two GitHub comments to remove that unsubscribe link. 

I would recommend that you either reply in github directly, or when replying to the github issue email that you remove `*@reply.github.com` as an email recipient.

**Comment by MikeTheSnowman** [comment]
Hey @JethaNh2 . After having a screensharing session with you, we determined that the issue is not with the connector. In all liklihood, the SSC server is probably getting overloaded by the number of REST API requests because you're running a call on the getIssueDetails endpoint for all issues across every issue in all applications.

The recommendation here is to either:
  - try refactoring the report so that you're not calling this function on all issues across all applications. 
  - or try adding additional CPU & RAM to the SSC server to see if that can help with the load that your report is putting on the server
